

services:
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - "1080:1080" # Web UI for viewing emails
      - "1025:1025" # SMTP server for sending emails
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge



