spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: postgres
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000

application:
  security:
    jwt:
      secret-key: 1d664d4762667d36d16527c7d4d6644141a277b73cdf7b849626fa46cee8a260
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account


server:
   port: 8088

